### Exercici 4: Pràctica amb programació numèrica

Familiaritza't amb la Programació Numèrica a través de la llibreria NumPy.

Nivell 1

- Exercici 1
Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [6]:
import numpy as np
from numpy import random

#proba feta amb una llista random d'una dimensió
#llista = random.randint (100,size =(10) )

#proba feta amb una llista random de dues dimensions
llista = random.randint (100,size =(2,10) )

print("Prenent la següent llista: \n", llista)

if np.ndim (llista) == 1:
    valormin  = np.amin(llista)
    valormax  = np.amax(llista)
    mediana   = np.median(llista)
    mitja     = np.average(llista)
    frq       = np.array(np.unique(llista, return_counts=True)).T
    print("hem calcul.lat els següents valors: \nValor mínim: ",valormin,"\nValor màxim: ", valormax)
    print("la mitja aritmètica es: ",mitja)
    print("valor mig: ",mediana, " \ni la freqüècia en q es donen els seus valors \n", frq)
else:
    print("ValueError, l'array és multidimensional")

Prenent la següent llista: 
 [[78  2 70 56 96 78 66 40 62 71]
 [95 81 93 59 62 85 24 88 37 19]]
ValueError, l'array és multidimensional


- Exercici 2
Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [2]:
import numpy as np
from numpy import random

quadrat = random.randint (100, size = (5,5))

print(quadrat)

[[59 25 56 73 51]
 [61 31  4 25 77]
 [90  8  1 80 11]
 [41 50 18 99 60]
 [66 54 96 39 25]]


- Exercici 3
Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.

In [11]:
import numpy as np
from numpy import random

llista = random.randint (10, size = (3,3))
print("Prenem la següent llista com a referència: \n", llista)
print("Els totals per fila són: \n ", np.sum(llista, axis=0))
print("i els totals per columna són: \n",np.sum(llista, axis=1))

Prenem la següent llista com a referència: 
 [[7 5 3]
 [6 9 0]
 [2 6 9]]
Els totals per fila són: 
  [15 20 12]
i els totals per columna són: 
 [15 15 17]


- Exercici 4
Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

In [16]:
import numpy as np
import scipy.stats

a = np.arange(5,10)
b = np.array([61, 31,  4, 25, 77])
r = np.corrcoef(a,b)
print(r)

[[1.         0.14077313]
 [0.14077313 1.        ]]
