### Exercici 1
Crea un np.array d'una dimensió, que inclogui l'almenys 8 nombres sencers, data type int64. Mostra la dimensió i la forma de la matriu. .

In [15]:
import numpy as np
from numpy import random

arr = random.randint(100, size = (8), dtype = np.int64)

#amb el mètode randint creem l'arry amb números aleatòris


tipusDades = arr.dtype
dimensio   = arr.ndim
forma      = arr.shape

print(f"El nou array és {newarr}, data type {tipusDades}, la seva dimensió és {dimensio} i la forma de la matriu és {forma}.")

El nou array és [11 73 50 38  3 31  7 54], data type int64, la seva dimensió és 1 i la forma de la matriu és (8,).


### Exercici 2
De la matriu de l'exercici 1, calcula el valor mitjà dels valors introduïts i resta la mitjana resultant de cada un dels valors de la matriu.

In [19]:
import numpy as np
from numpy import random

arr = random.randint(100, size = (8), dtype = np.int64)

#com es tracta d'un array random, i serà diferent cada cop q executem el programa,
#he decidir imprimir-ho per pantalla perque sigui més fàcil de comprobar, però no caldria.
print(arr)
print(np.median(arr))
m = np.median(arr) # aquí calcul.lo el valor mig i el gaurdo a la variable m
newarr = arr - m   #faig la resta i dono per pantalla el resultat
print(newarr)

[22 69 79 32 42 89 32 91]
55.5
[-33.5  13.5  23.5 -23.5 -13.5  33.5 -23.5  35.5]


### Exercici 3
Crea una matriu bidimensional amb una forma de 5 x 5. Extreu el valor màxim de la matriu, i els valors màxims de cadascun dels seus eixos.

In [29]:
import numpy as np
from numpy import random

arr = random.randint (100, size = (5,5))

print(arr)
print("El valor màxim de la matriu és: ", np.amax(arr))
print("El valor màxim de l'eix horitzontal és: ",np.amax(arr,0))
print("El valor màxim de l'eix vertical és: ",np.amax(arr,1))

[[14 38 21 69 30]
 [51  8  0 67 50]
 [ 2  8 71 85 92]
 [38 63 49 76 43]
 [61 98 98 35 63]]
El valor màxim de la matriu és:  98
El valor màxim de l'eix horitzontal és:  [61 98 98 85 92]
El valor màxim de l'eix vertical és:  [69 67 92 76 98]
