# Nivell 2

Treballem els conceptes de l'estructura d'una matriu, Broadcasting, indexació, Mask..

### Exercici 4
Mostreu-me amb exemples de diferents matrius, la regla fonamental de Broadcasting que diu : "les matrius es poden transmetre / broadcast si les seves dimensions coincideixen o si una de les matrius té una mida d'1".



Com genralment Numpy opera element per element, per tal de poder operar els arrays has de tenir la mateixa "shape", o tenir la mida d'un element.
El Broadcast permet "stirar", "repetir", " prendre" el valor donat i operar amb ell i cada element de la matriu.


In [46]:
""" Exemple 1, operant amb un escalar i una matriu de 3x4.
    En aquest cas, és com si el broadcast "tingués en memòria" un array b de les mateixes dimensions q l'array "arr" i 
    operés amb cada element.
"""


import numpy as np
from numpy import random

arr = random.randint (100, size = (3,4))

b = 2.0

c = random.randint(100, size=(4))

print("array original A:\n", arr)
print("\narray producte:\n", arr*b)
print("\narray suma:\n", arr + b)

print("array C:\n", c)
print("\narray producte:\n", arr*c)
print("\narray suma:\n", arr + c)

array original A:
 [[26 13 55 39]
 [18 14 30  4]
 [ 3 57 24 87]]

array producte:
 [[ 52.  26. 110.  78.]
 [ 36.  28.  60.   8.]
 [  6. 114.  48. 174.]]

array suma:
 [[28. 15. 57. 41.]
 [20. 16. 32.  6.]
 [ 5. 59. 26. 89.]]
array C:
 [47 10 77 60]

array producte:
 [[1222  130 4235 2340]
 [ 846  140 2310  240]
 [ 141  570 1848 5220]]

array suma:
 [[ 73  23 132  99]
 [ 65  24 107  64]
 [ 50  67 101 147]]


In [45]:
""" Exemple 2, operant amb arrays de diferent mida, obtindrem un error. 
    ValueError: operands could not be broadcast together with shapes (5,) (3,) 
    
"""


import numpy as np
from numpy import random

arr = random.randint(100, size=(5))

b = random.randint(100, size=(3))

print("array original A:\n", arr)
print("array original B:\n", b)
print("array producte:\n", arr * b)
print("array suma:\n", arr + b)

array original A:
 [38  8 46 33 39]
array original B:
 [91 39 95]


ValueError: operands could not be broadcast together with shapes (5,) (3,) 

### Exercici 5
Utilitza la Indexació per extreure els valors d'una columna i una fila de la matriu. I suma els seus valors.


In [59]:
import numpy as np
from numpy import random

arr = random.randint (50, size = (3,3))

print(f"\nDe l'array de mostra,\n {arr}\nn'extreurem el segon valor del primer array i el tercer del segon array, valors : ",arr[0,1], "i", arr[1,2], "i els sumem.\nTotal:", arr[0,1]+arr[1,2] )
print()




De l'array de mostra,
 [[48  3 10]
 [43 49 44]
 [35  0 14]]
n'extreurem el segon valor del primer array i el tercer del segon array, valors :  3 i 44 i els sumem.
Total: 47



### Exercici 6
Mask la matriu anterior, realitzeu un càlcul booleà vectoritzat, agafant cada element i comprovant si es divideix uniformement per quatre.

Això retorna una matriu de mask de la mateixa forma amb els resultats elementals del càlcul.



In [83]:
"""
en aquest primer exemple he creat la mask directament.
"""
import numpy as np
import numpy.ma as ma


arr = np.array([[48,3,10], [43,49,44],[35, 0 ,14]])

print("array inicial\n" ,arr,"\n")
print("matriu de mask booleana\n", arr % 4 ==0)




array inicial
 [[48  3 10]
 [43 49 44]
 [35  0 14]] 

matriu de mask booleana
 [[ True False False]
 [False False  True]
 [False  True False]]


In [85]:
"""
També he mirat de donar resposta a l'exercici anterior amb la funció masked_were() que m'ha tornat els valors dels elements
q no complien la condició.

"""


import numpy as np
import numpy.ma as ma

arr = np.array([[48,3,10], [43,49,44],[35, 0 ,14]])
print("array inicial\n" ,arr)
mask_arr = np.ma.masked_where(arr % 4 ==0, arr, copy=True )
print("array mask, on només apareixen els elements q no compleixen la condició\n" , mask_arr)

array inicial
 [[48  3 10]
 [43 49 44]
 [35  0 14]]
array mask, on només apareixen els elements q no compleixen la condició
 [[-- 3 10]
 [43 49 --]
 [35 -- 14]]


### Exercici 7
A continuació, utilitzeu aquesta màscara per indexar a la matriu de números original. Això fa que la matriu perdi la seva forma original, reduint-la a una dimensió, però encara obteniu les dades que esteu cercant.

In [84]:
import numpy as np
import numpy.ma as ma

arr = np.array([[48,3,10], [43,49,44],[35, 0 ,14]])
mask_arr2 = arr[arr % 4 ==0]

print("array inicial\n" ,arr)
print("array mask, on només apareixen els elements q acompleixen la condició\n" , mask_arr2)

array inicial
 [[48  3 10]
 [43 49 44]
 [35  0 14]]
array mask, on només apareixen els elements q no compleixen la condició
 [48 44  0]
